# -----------------------------------------------------------------------------
# PROJECT: Dual-Zone OpenTherm S-Plan Controller
# DEVICE: ESP32 NodeMCU / Wemos D1 Mini ESP32
# DESCRIPTION: PID modulated heating with logic interlocks for external valves.
# -----------------------------------------------------------------------------

substitutions:
  devicename: "central-heating-controller"
  friendly_name: "Heating Logic Board"
  # Boiler Limits
  max_flow_temp: "70.0"   # Maximum water temp the boiler is allowed to output
  min_flow_temp: "35.0"   # Minimum effective temp (below this, efficiency gains diminish or boiler cycles)
  # PID Thresholds
  pid_deadband: "0.05"    # 5% demand required to open valves (prevents micro-firing)

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: wemos_d1_mini32 #nodemcu-32s  # Change to 'wemos_d1_mini32' if using the D1 Mini form factor
  framework:
    type: arduino

# -----------------------------------------------------------------------------
# LOGGING & DEBUGGING
# -----------------------------------------------------------------------------
logger:
  level: DEBUG
  baud_rate: 115200
  logs:
    esp32_ble_tracker: WARN
    sensor: INFO
    binary_sensor: INFO

# -----------------------------------------------------------------------------
# CONNECTIVITY
# -----------------------------------------------------------------------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fb_hotspot_ssid_D1mini_opentherm
    password: !secret fb_hotspot_pw_D1mini_opentherm

# Home Assistant API
api:
  encryption:
    key: !secret HAapikey_D1mini_opentherm

ota:
  - platform: esphome
    password: !secret otapw_D1mini_opentherm

# -----------------------------------------------------------------------------
# HARDWARE: OPENTHERM
# -----------------------------------------------------------------------------
opentherm:
  in_pin: 21   # ESP32 RX <- Shield OUT
  out_pin: 22  # ESP32 TX -> Shield IN
  id: ot_hub

# We must define these entities so we can control them from lambdas/scripts
number:
  - platform: opentherm
    t_set:
      id: ot_t_set
      name: "Boiler Control Setpoint"
      min_value: 0
      max_value: 90
      step: 1

switch:
  - platform: opentherm
    ch_enable:
      id: ot_ch_enable
      name: "Boiler CH Enabled"

# -----------------------------------------------------------------------------
# HARDWARE: BLUETOOTH SENSORS (XIAOMI PVVX)
# -----------------------------------------------------------------------------
esp32_ble_tracker:
  scan_parameters:
    interval: 300ms
    window: 200ms

sensor:
  # ---------------------------------------------------------------------------
  # Temperature Inputs
  # ---------------------------------------------------------------------------
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:AA:DC:57"  # <--- UPDATE THIS REAL MAC
    temperature:
      name: "Downstairs Room Temp"
      id: temp_downstairs
    humidity:
      name: "Downstairs Humidity"
    battery_level:
      name: "Downstairs Battery"

  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:57:0F:22"  # <--- UPDATE THIS REAL MAC
    temperature:
      name: "Upstairs Room Temp"
      id: temp_upstairs
    humidity:
      name: "Upstairs Humidity"
    battery_level:
      name: "Upstairs Battery"

  # ---------------------------------------------------------------------------
  # Boiler Feedback Sensors (OpenTherm)
  # ---------------------------------------------------------------------------
  - platform: opentherm
    t_boiler:
      name: "Boiler Flow Temperature"
      id: boiler_actual_flow
    t_ret:
      name: "Boiler Return Temperature"
    rel_mod_level:
      name: "Boiler Modulation"
      id: boiler_mod_level
    ch_pressure:
      name: "System Pressure"

# -----------------------------------------------------------------------------
# INPUTS: VALVE STATUS FROM HOME ASSISTANT
# -----------------------------------------------------------------------------
binary_sensor:
  - platform: homeassistant
    name: "Valve Downstairs End-Stop"
    entity_id: binary_sensor.kincody_valve_valve_downstairs_open
    id: valve_fb_downstairs
  
  - platform: homeassistant
    name: "Valve Upstairs End-Stop"
    entity_id: binary_sensor.kincody_valve_valve_upstairs_open
    id: valve_fb_upstairs

  # Boiler Status
  - platform: opentherm
    flame_on:
      name: "Flame Status"
    fault_indication:
      name: "Fault Status"

# -----------------------------------------------------------------------------
# LOGIC STORE: GLOBAL VARIABLES
# -----------------------------------------------------------------------------
globals:
  - id: pid_out_downstairs
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: pid_out_upstairs
    type: float
    restore_value: no
    initial_value: '0.0'

# -----------------------------------------------------------------------------
# CLIMATE CONTROLLERS (PID)
# -----------------------------------------------------------------------------
climate:
  # Downstairs Controller
  - platform: pid
    name: "Downstairs Thermostat"
    id: cli_down
    sensor: temp_downstairs
    default_target_temperature: 20
    heat_output: out_pid_down
    control_parameters:
      kp: 0.6
      ki: 0.005
      kd: 1.5
    visual:
      min_temperature: 10
      max_temperature: 25
      temperature_step: 0.5

  # Upstairs Controller
  - platform: pid
    name: "Upstairs Thermostat"
    id: cli_up
    sensor: temp_upstairs
    default_target_temperature: 19
    heat_output: out_pid_up
    control_parameters:
      kp: 0.6
      ki: 0.005
      kd: 1.5
    visual:
      min_temperature: 10
      max_temperature: 25
      temperature_step: 0.5

# -----------------------------------------------------------------------------
# OUTPUT INTERCEPTION (The Logic Layer)
# -----------------------------------------------------------------------------
output:
  - platform: template
    id: out_pid_down
    type: float
    write_action:
      - lambda: |-
          id(pid_out_downstairs) = state;
      - if:
          condition:
            lambda: 'return state > ${pid_deadband};'
          then:
            - homeassistant.service:
                service: switch.turn_on
                data:
                  entity_id: switch.kincody_valve_relay_downstairs
          else:
            - homeassistant.service:
                service: switch.turn_off
                data:
                  entity_id: switch.kincody_valve_relay_downstairs
      - script.execute: arbitrate_boiler_demand

  - platform: template
    id: out_pid_up
    type: float
    write_action:
      - lambda: |-
          id(pid_out_upstairs) = state;
      - if:
          condition:
            lambda: 'return state > ${pid_deadband};'
          then:
            - homeassistant.service:
                service: switch.turn_on
                data:
                  entity_id: switch.kincody_valve_relay_upstairs
          else:
            - homeassistant.service:
                service: switch.turn_off
                data:
                  entity_id: switch.kincody_valve_relay_upstairs
      - script.execute: arbitrate_boiler_demand

# -----------------------------------------------------------------------------
# MASTER ARBITRATION SCRIPT (The Interlock)
# -----------------------------------------------------------------------------
script:
  - id: arbitrate_boiler_demand
    mode: restart
    then:
      - lambda: |-
          // 1. Fetch Configuration & State
          float max_t = ${max_flow_temp};
          float deadband = ${pid_deadband};
          
          float d_req = id(pid_out_downstairs);
          float u_req = id(pid_out_upstairs);
          
          bool d_open = id(valve_fb_downstairs).state;
          bool u_open = id(valve_fb_upstairs).state;
          
          // 2. Debugging Output
          ESP_LOGD("logic", "=== HEATING LOGIC CYCLE ===");
          ESP_LOGD("logic", "DOWNSTAIRS: Demand %.1f%% | Valve: %s", d_req * 100.0, d_open? "OPEN" : "CLOSED");
          ESP_LOGD("logic", "UPSTAIRS:   Demand %.1f%% | Valve: %s", u_req * 100.0, u_open? "OPEN" : "CLOSED");
          
          // 3. Calculate Temperature Requirement per Zone
          float d_target_temp = 0.0;
          float u_target_temp = 0.0;
          
          if (d_req > deadband) {
            if (d_open) {
              d_target_temp = d_req * max_t;
              ESP_LOGD("logic", ">> Downstairs Valid: Requesting %.1f C", d_target_temp);
            } else {
              ESP_LOGW("logic", ">> Downstairs WAITING: Valve not yet confirmed open.");
            }
          }
          
          if (u_req > deadband) {
            if (u_open) {
              u_target_temp = u_req * max_t;
              ESP_LOGD("logic", ">> Upstairs Valid: Requesting %.1f C", u_target_temp);
            } else {
              ESP_LOGW("logic", ">> Upstairs WAITING: Valve not yet confirmed open.");
            }
          }
          
          // 4. Aggregate Demand (MAX Operator)
          float final_setpoint = 0.0;
          if (d_target_temp > final_setpoint) final_setpoint = d_target_temp;
          if (u_target_temp > final_setpoint) final_setpoint = u_target_temp;
          
          // 5. Minimum Boiler constraints
          if (final_setpoint > 0 && final_setpoint < ${min_flow_temp}) {
             final_setpoint = ${min_flow_temp};
             ESP_LOGD("logic", ">> Clamping to minimum flow temp %.1f C", final_setpoint);
          }
          
          // 6. Execute OpenTherm Command via Number Entity
          ESP_LOGI("logic", ">>> FINAL BOILER COMMAND: Setpoint %.1f C", final_setpoint);
          
          auto call = id(ot_t_set).make_call();
          call.set_value(final_setpoint);
          call.perform();
          
          // 7. Explicit CH Enable via Switch Entity
          if (final_setpoint > 0) {
            if (!id(ot_ch_enable).state) {
               id(ot_ch_enable).turn_on();
            }
          } else {
            if (id(ot_ch_enable).state) {
               id(ot_ch_enable).turn_off();
            }
          }
