# Basic Config
esphome:
  name: kincody-valve

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret HAapikey_Kincody_valve

ota:
- platform: esphome
  password: !secret otapw_Kincody_valve

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fb_hotspot_ssid_Kincody_valve
    password: !secret fb_hostspot_pw_Kincody_valve

captive_portal:

switch:
  - platform: gpio
    name: "relay-downstairs"
    pin: 
      number: GPIO02
      inverted: false

  - platform: gpio
    name: "relay-upstairs"
    pin: 
      number: GPIO15
      inverted: false

binary_sensor:
  - platform: gpio
    name: "valve-downstairs-open"
    device_class: opening
    pin:
      number: GPIO36
      inverted: true
    filters:
      - delayed_on_off: 100ms

  - platform: gpio
    name: "valve-upstairs-open"
    device_class: opening
    pin:
      number: GPIO39
      inverted: true
    filters:
      - delayed_on_off: 100ms
