esphome:
  name: test
#  on_boot:
#    - lambda: |-
#        id(my_ota).set_auth_password("eBW7K0AQcH5fh0Eb482T");

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret HAapikey_nodemcu_test

ota:
  - platform: esphome
    password: !secret otapw_nodemcu_test
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fb_hotspot_ssid_nodemcu_test
    password: !secret fb_hotspot_pw_nodemcu_test

captive_portal:
    
switch:

one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: dallas_temp
    address: 0x31000006dd93e628
    name: "Test temp"
    accuracy_decimals: 2
