esphome:
  name: office_bench
#  on_boot:
#    - lambda: |-
#        id(my_ota).set_auth_password("LDKmR4wWc6kmsBOcYwzG");

esp8266:
  board: sonoff_basic

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret HAapikey_sonof_office_bench

ota:
  - platform: esphome
    password: !secret otapw_sonof_office_bench
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fb_hotspot_ssid_sonof_office_bench
    password: !secret fb_hotspot_pw_sonof_office_bench

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Office Strip Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Office Strip"
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
